version: "3.8"

services:
  rstudio:
    build: .
    ports:
      - "8787:8787"
    volumes:
      - ./dados:/home/rstudio/dados
    depends_on:
      - neo4j
    networks:
      - bigdata

  neo4j:
    image: neo4j:4.4
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/conf:/conf
    environment:
      - NEO4J_AUTH=neo4j/admin123
      - NEO4J_dbms_connector_bolt_advertised__address=localhost:7687
      - NEO4J_dbms_connector_http_advertised__address=localhost:7474
      - NEO4J_dbms_connector_http_listen__address=0.0.0.0:7474
      - NEO4J_dbms_connector_bolt_listen__address=0.0.0.0:7687
    networks:
      - bigdata

networks:
  bigdata:
